### ISSUE TITLE
hcitool lescan (Bluetooth LE or any bluetooth scan) in docker under Non-Privileged & Non-host Network mode is possible ?

### ISSUE THREAD

**Issue by linux-edwin** [jessfraz/dockerfiles#309] opened 2017-11-10 07:48 UTC
Hello @jessfraz  and docker users,
I am a newbie to docker. For a specific task, I am failing to scan BLE or BlueZ in docker **under Non-Privileged & Non-Host network** mode.
These are my results > (in Debian-Jessie-8.8.0 Host and debian:jessie docker image)
`root1@73ab53a9268e:/#  hciconfig -a
Can't open HCI socket.: Operation not permitted`
and -
`root1@73ab53a9268e:/#  bt-device -l
Couldn't connect to DBus system bus: Could not connect: Connection refused`
another image -
`root2@0d208802d44a:/# hciconfig -a
Can't open HCI socket.: Address family not supported by protocol`
I even gave ALL-CAP permissions for docker on Host but still could not make it.
`docker run --name container-ID --cap-add=ALL -d -v /var/run/docker.sock:/host/var/run/docker.sock
-v /dev:/host/dev -v /proc:/host/proc:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro Image-ID`
So, is it possible by any chance ?

**Comment by linux-edwin** [comment] 2017-11-17 09:56
Half  Success :+1:

**Comment by linux-edwin** [comment] 2017-11-20 06:58
Almost Done...!  Bluetooth Scan Works by adding the below Flags.
**--cap-add=SYS_ADMIN**   and
**-v /opt/bluetooth:/var/lib/bluetooth -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /tmp/$(mktemp -d):/run**

CMD_USED :  `edwin@debian:~$ docker run --cap-add=SYS_ADMIN *-v /opt/bluetooth:/var/lib/bluetooth -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /tmp/$(mktemp -d):/run* --net=host -it debian:jessie`

Next I am looking to run docker with :  "not to share the Host Networking Namespace"

**Comment by linux-edwin** [comment] 2017-11-20 07:16
Almost Done...!

With help from Docker Community, **First I have Successfully Started DBus Service** inside docker container by logging in docker as follows :

`docker run -v /opt/bluetooth:/var/lib/bluetooth -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /tmp/$(mktemp -d):/run -it debian:jessie`

Then by adding **--cap-add=SYS_ADMIN** and **--net=host** this permission, Possible to start bluetooth service.

`docker run --cap-add=SYS_ADMIN -v /opt/bluetooth:/var/lib/bluetooth -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /tmp/$(mktemp -d):/run --net=host -it debian:jessie`

Now just looking to start bluetooth service by "Not sharing the Host Networking Namespace"  (customising --net=host to private network)

If somebody got any Clue, that would be helpful.

**Comment by rcauquil** [comment] 2018-02-01 16:44
any news on this ?

**Comment by jessfraz** [comment] 2018-06-06 21:31
closing as this is not a bug with the repo but feel free to discuss more

**Closed by jessfraz** 2018-06-06 21:31 UTC
Labels: question

**Comment by hktalent** [comment] 2018-09-26 07:01
```
dckImg="kali-linux20180920_211247"
dckc="0df459aa83e0"

docker run -it --cap-add=SYS_ADMIN --cap-add=NET_ADMIN  --net=host --expose 80-65530 -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --device /dev/cu.Bluetooth-Incoming-Port --device /dev/tty.Bluetooth-Incoming-Port --privileged  --name='kali-linux2018091d' $dckImg /bin/bash

```
