### ISSUE TITLE
wireguard /bin/sh: ./scripts/recordmcount: not found

### ISSUE THREAD

**Issue by Mehran** [jessfraz/dockerfiles#439] opened 2018-11-05 06:38 UTC
```
Unable to find image 'jess/wireguard:install' locally
install: Pulling from jess/wireguard
Digest: sha256:6f76f0dace448b0b64793f250800a87a8d9ff05e5f1a816384aa6e3965e6f362
Status: Downloaded newer image for jess/wireguard:install
Building the wireguard kernel module...
  CC [M]  /wireguard/src/main.o
/bin/sh: ./scripts/recordmcount: not found
make[2]: *** [scripts/Makefile.build:278: /wireguard/src/main.o] Error 127
make[1]: *** [Makefile:1439: _module_/wireguard/src] Error 2
make: *** [Makefile:36: module] Error 2
```

**Comment by koep** [comment] 2018-11-05 07:29
Duplicate of #403.

**Closed by koep** 2018-11-05 07:29 UTC
